myproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('user.urls','user'),namespace="user")),
]

user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name="index"),
    path('navi',views.nav,name="nav"),
]

user/models.py
from django.db import models

# Create your models here.

user/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'user/index.html')

def nav(request):
    return render(request,'user/navigation.html')

user/templates/user/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

</body>
</html>

user/templates/user/navigation.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{%static 'static\user\main.css' %}">
</head>
    <body>
        <div class="navbar">
            <a href ="{%url 'user:nav' %}">Aboutus</a>
            <a href ="{%url 'user:nav' %}">Blog</a>
            <a href ="{%url 'user:nav' %}">Sign In</a>
            <a href="{%url 'user:nav' %}"> Signup</a>
        </div>
    </body>
</html>